name: Weekly OCHA Gaza Snapshot

on:
  schedule:
    - cron: '0 6 * * 4'   # 毎週水曜 15:00 JST（06:00 UTC）
  workflow_dispatch:       # 手動実行も可

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scripts/scrape.py

      - name: Commit & push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name  "github-actions[bot]"
          git add data/*.csv plots/*.png
          git diff --cached --quiet || git commit -m "Update snapshot data ($(date -u +'%Y-%m-%d'))"
          git push
        env:
          # GITHUB_TOKEN はデフォルトで渡ってくるので特別な設定は不要
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
